[build]
  command = "npm run build"
  publish = ".next"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF ./"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NEXT_USE_NETLIFY_EDGE = "true"
  NODE_VERSION = "18"
  NEXT_TELEMETRY_DISABLED = "1"

[build.processing]
  skip_processing = true

[functions]
  included_files = [".next/standalone/**"]

# Força limpeza do cache
[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
  FORCE_CACHE_CLEAR = "true"